name: dbt CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build de l’image Docker dbt
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dbt-image:latest .

      # Push sur Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dbt-image:latest

      # Lancement des tests dbt dans le container
      - name: Run dbt tests
        run: |
          docker run --rm \
            -e DBT_HOST=${{ secrets.PGHOST }} \
            -e DBT_PORT=${{ secrets.PGPORT }} \
            -e DBT_USER=${{ secrets.PGUSER }} \
            -e DBT_PASSWORD=${{ secrets.PGPASSWORD }} \
            -e DBT_DBNAME=${{ secrets.PGDATABASE }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/dbt-image:latest test

