# configuration globale
global:
  scrape_interval: 15s # Par défaut, scrape les cibles toutes les 15 secondes.
  evaluation_interval: 15s # Par défaut, scrape les cibles toutes les 15 secondes.
  # scrape_timeout est défini sur la valeur globale par défaut (10 s).

  # Etiquettes à attacher à toute série chronologique ou alertepour communiquer avec
  # systèmes externes (fédération, stockage distant, Alertmanager).
  external_labels:
    monitor: "projet-avril25_cde_airlines"

# Chargement et évaluation des règles dans ce fichier toutes les 'evaluation_interval' secondes.
rule_files:
  - "recording_rules.yml"
  - "alerting_rules.yml"
  - "alerts/*.yml"
# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

# Une configuration de scrape contenant exactement un endpoint à scraper :
# Ici, c'est Prometheus lui-même.
scrape_configs:
  # Le nom de la tâche est ajouté en tant qu'étiquette `job=<job_name>` à toutes les séries temporelles extraites de cette configuration.

  - job_name: "prometheus"

    scrape_interval: 5s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"

    scrape_interval: 5s

    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"

    scrape_interval: 5s

    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: 'postgres'

    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: "fastapi"

    scrape_interval: 5s

    static_configs:
      - targets: ["airlines_fastapi:8000"]
